Submitting LEXIS DDL for review
bcgov/nr-permitting-ddls pull request #1
Opened 2024-02-02 19:24 UTC by JTA2020

2024-02-22 17:46 UTC, abimichel requested changes
Looks great! Just a few quick edits. I updated this page so others know what formatting needs to be done: https://apps.nrs.gov.bc.ca/int/confluence/x/bpMlCw

2024-02-22 17:46 UTC, abimichel commented on LEXIS/export_permit_detail.sql
> +-- SQLINES DEMO *** _DETAIL definition
These comments can be deleted

2024-02-22 17:46 UTC, abimichel commented on LEXIS/export_permit_detail.sql
> +CREATE TABLE THE.EXPORT_PERMIT_DETAIL (
schema should be 'lexis_replication'

2024-02-22 17:46 UTC, abimichel commented on LEXIS/export_permit_detail.sql
> +	CONSTRAINT SYS_C00233033 CHECK ("EXPORT_PERMIT_DETAIL_NUMBER" IS NOT NULL),
check constraints can be deleted

2024-02-22 17:46 UTC, abimichel commented on LEXIS/export_permit_detail.sql
> +ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
foreign keys can be deleted

2024-03-06 00:52 UTC, JTA2020 commented
Changes made, please advise!

2024-03-08 16:56 UTC, abimichel approved these changes

2024-03-08 16:56 UTC, merged